### ISSUE TITLE
Support for optional parameters

### ISSUE THREAD

**Issue by CUnknown** [ElMassimo/js_from_routes#2]
We have a scope in our routes with an optional parameter: 
 ```
scope '(:locale)', locale: Regexp.new(I18n.available_locales.join('|')) do
end
```
Using your generator, this wil result in the following JS routes:
```
export default {
  get: options =>
    request('get', '(/:locale)/users/:id', options),

```

And the `(/:locale)` will be resolved to `(/en)` for English, so the resulting JS path will be somthing like: `(/en)/users/123` and this is not a valid path.

Could you look into this? Thanks!

**Comment by ElMassimo** [comment]
Since the parameter is optional, it should probably be handled internally in [the function that is used to interpolate the url](https://github.com/ElMassimo/js_from_routes/blob/master/spec/support/sample_app/app/javascript/helpers/UrlHelper.js#L7-L20).

The function provided in the code samples is just an example, you may extend that to support optional parameters.

Haven't For example:

```js
const REQUIRED_PARAMETER = /:[^\W\d]+/g
const OPTIONAL_PARAMETER = /\(\/:[^\W\d]+\)/g

// Public: Replaces any placeholder in the string with the provided parameters.
function interpolate (template, params) {
  let value = template.toString()
  for (const paramName in params) {
    value = value
      .replace(`(/:${snakeCase(paramName)})`, `/${params[paramName]}`) // Optional Parameters
      .replace(`:${snakeCase(paramName)}`, params[paramName])
  }

  // Remove any optional path if the parameters were not provided.
  value = value.replace(OPTIONAL_PARAMETER, '')

  const missingParams = value.match(REQUIRED_PARAMETER)
  if (missingParams) {
    const missing = missingParams.join(', ')
    const provided = params && Object.keys(params).join(', ')
    throw new TypeError(`Missing ${missing} for ${template}. Params provided: ${provided}`)
  }
  return value
}
```

which might achieve what you need:

```js
interpolate('(/:locale)/users/:id', { locale: 'en', id: 5 })
"/en/users/5"
interpolate('(/:locale)/users/:id', { id: 5 })
"/users/5"
```

**Comment by ElMassimo** [comment]
@CUnknown Starting in `2.0.0` client libraries are provided, such as `@js-from-routes/client`, which has baked-in support for optional parameters.

Unlike required parameters, when optional parameters are not passed no exception is thrown.
