### ISSUE TITLE
Adjust Regex for parameter right before optional parameter

### ISSUE THREAD

**Issue by danieldiekmeier** [ElMassimo/js_from_routes#26]
Hey, thanks for your work on this project and on all the Vite tooling for Rails, it's very much appreciated!

I'm in the process of adding `js_from_routes` to a project, but I noticed a problem where I couldn't generate a path for one of my URLs.

```js
import { definePathHelper } from '@js-from-routes/client'
const get = definePathHelper('get', '/by/:username(/:page)')
console.log(get.path({ username: 'example' }))

// Throws: Uncaught (in promise) TypeError: Missing URL Parameter :username for /by/:username(/:page). Params provided: username
```

I dug into the source code and I think the problem is that the regex which replaces the parts of the path expects params to be followed by either `/`, `.` or the end of the string.

I used [patch-package](https://www.npmjs.com/package/patch-package) to add another case, where the next character could be a `(`, and everything started working. Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@js-from-routes/core/dist/index.js b/node_modules/@js-from-routes/core/dist/index.js
index 6e59e69..0fabcd1 100644
--- a/node_modules/@js-from-routes/core/dist/index.js
+++ b/node_modules/@js-from-routes/core/dist/index.js
@@ -112,7 +112,7 @@ function interpolateUrl(template, params) {
   let value = template.toString();
   Object.entries(params).forEach(([paramName, paramValue]) => {
     paramName = snakeCase(paramName);
-    value = value.replace(new RegExp(escapeRegExp(`(/:${paramName})`), "g"), `/${paramValue}`).replace(new RegExp(`:${escapeRegExp(paramName)}(\\/|\\.|$)`, "g"), `${paramValue}$1`);
+    value = value.replace(new RegExp(escapeRegExp(`(/:${paramName})`), "g"), `/${paramValue}`).replace(new RegExp(`:${escapeRegExp(paramName)}(\\/|\\.|\\(|$)`, "g"), `${paramValue}$1`);
   });
   value = value.replace(OPTIONAL_PARAMETER, "");
   const missingParams = value.match(REQUIRED_PARAMETER);
```

It would be great to see this fixed in the package itself! Thanks for your consideration.

**Comment by ElMassimo** [comment]
Hi Daniel! @danieldiekmeier 

Thanks for reporting this, optional parameters is something I added in a later version and seems like I didn't cover this case.

Happy to accept a PR if you would like to make one, or I can make one with your patch :smiley:

**Comment by danieldiekmeier** [comment]
I added a test case and created a PR in #27. Thanks!

**Comment by peytonpeck** [comment]
Hello, in trying to use `definePathHelper` with optional routes, I noticed some issues with how the interpolation works. I created a PR to resolve the issue with a good amount of tests!

https://github.com/ElMassimo/js_from_routes/pull/61
