### ISSUE TITLE
Not generating confirmations_controller routes for devise gem.

### ISSUE THREAD

**Issue by siba2893** [ElMassimo/js_from_routes#33]
[troubleshooting section]: https://js-from-routes.netlify.app/faqs/

- [X] I have tried upgrading by running `bundle update js_from_routes`.
- [X] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

Hey I was trying for the Rails + Vite + Vue 3 + Inertia.js combo, while comparing the Original Demo App vs your version of the Demo App, I love the gem that you built called `js_from_routes` its quite cool. 

But I encounter a problem, for some reason the gem doesn't want to generate the `users/confirmations_controller` routes for Devise, it does generate the `sessions, registrations, passwords` but not the confirmations. 

You can see at the screenshot how all the other controllers are there as Api routes.

### Reproduction/Logs 🐞📜

Add the confirmations_controller in your devise example app and try to see if it generates the routes.

### Screenshots 📷

<img width="1750" alt="Captura de Pantalla 2022-08-03 a la(s) 7 37 58 p  m" src="https://user-images.githubusercontent.com/2425158/182744415-3d4e663a-1dec-4e4f-8331-e723d4569b8d.png">

**Comment by ElMassimo** [comment]
Hi Daniel, please share a repo with a minimal reproduction and I'll take a look.

I tested in an app, and it generated confirmations as well:

```ts
// JsFromRoutes CacheKey d373e19a0694ae472b5b76beaad73f93
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '~/services/api'

export default {
  new: definePathHelper('get', '/users/confirmation/new'),
  show: definePathHelper('get', '/users/confirmation'),
  create: definePathHelper('post', '/users/confirmation'),
}
```

**Comment by ElMassimo** [comment]
If you run `bin/rails routes | grep confirmations` in the app, you will notice there are no routes for `confirmations`, which is the reason why `js_from_routes` is not generating helpers.

The reason Devise is not adding those routes is probably related to the [Devise configuration](https://stackoverflow.com/a/47344222/747418), you must add `:confirmable` to the `User` model.

**Comment by siba2893** [comment]
OMG thank you so much for finding the out.
