### ISSUE TITLE
Uninitialized constant #<Class:JsFromRoutes>::OpenStruct

### ISSUE THREAD

**Issue by noxasch** [ElMassimo/js_from_routes#47]
[troubleshooting section]: https://js-from-routes.netlify.app/faqs/

- [x] I have tried upgrading by running `bundle update js_from_routes`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

When I have certain gems in my rails app, I hit by this error. 

```sh
> bundle exec rails js_from_routes:generate
bin/rails aborted!
NameError: uninitialized constant #<Class:JsFromRoutes>::OpenStruct (NameError)

      @config ||= OpenStruct.new(default_config(::Rails.root || Pathname.new(Dir.pwd)))
                  ^^^^^^^^^^
/home/noxasch/codes/rails-inertia-vue/config/initializers/js_from_routes.rb:2:in `<top (required)>'
/home/noxasch/codes/rails-inertia-vue/config/environment.rb:5:in `<top (required)>'
```

### Reproduction/Logs 🐞📜

can checkout my experiment repo `https://github.com/noxasch/rails-vite-inertia-vue`

**Comment by noxasch** [comment]
adding `require 'ostruct'` in application.rb seems to resolve this. Probably have conflict with some other gems.

Another solution is to to properly `require 'ostruct'` in `js_from_routes/lib/js_from_routes/generator.rb`

**Comment by Shaglock** [comment]
Happened to me after ruby 3.3.5 upgrade. 

Also added to `application.rb`, but there is a warning.

```
/Users/me/.local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/ostruct.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning
```
